# 1.20.1 metadata variant for the legacy NeoForge loader.
modLoader = "javafml"
loaderVersion = "${loader_version}"
license = "GPL-3.0-only"
issueTrackerURL = "https://github.com/MajorBonghits/ModernCompanions/issues"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
authors = "${mod_author}; original: justinwon777"
description = '''
Modern Companions is a NeoForge port and rebrand of the Human Companions mod. All original companion gameplay, entities, and structures will be brought forward while preserving attribution and GPL-3.0 licensing.
'''

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "curios"
mandatory = false
versionRange = "${curios_version_range}"
ordering = "NONE"
side = "BOTH"
